### ISSUE TITLE
query_stations.js throws exception

### ISSUE THREAD

**Issue by khassel** [raywo/MMM-PublicTransportHafas#36]
Hi,

thanks for the great module!

I'm getting the following error executing the query_stations.js on my raspi.
The Script works without the 2 references on 'arrayunique', so i could query my station anyway ...

```
module.js:472
    throw err;
    ^

Error: Cannot find module 'array-unique'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/magic_mirror/modules/MMM-PublicTransportHafas/convenience/query_stations.js:6:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

```

**Comment by raywo** [comment]
Did you run `npm install`?

**Comment by khassel** [comment]
yes. 
```
root@raspi3:/opt/magic_mirror/modules/MMM-PublicTransportHafas# npm install
npm info it worked if it ends with ok
npm info using npm@4.1.2
npm info using node@v7.6.0
npm info lifecycle MMM-PublicTransportHafas@1.0.2~preinstall: MMM-PublicTransportHafas@1.0.2
npm info linkStuff MMM-PublicTransportHafas@1.0.2
npm info lifecycle MMM-PublicTransportHafas@1.0.2~install: MMM-PublicTransportHafas@1.0.2
npm info lifecycle MMM-PublicTransportHafas@1.0.2~postinstall: MMM-PublicTransportHafas@1.0.2
npm info ok
root@raspi3:/opt/magic_mirror/modules/MMM-PublicTransportHafas# node ./convenience/query_stations.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'array-unique'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/magic_mirror/modules/MMM-PublicTransportHafas/convenience/query_stations.js:6:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

```

**Comment by raywo** [comment]
I forgot to require this module. A fix is underway.

**Comment by raywo** [comment]
Just merged the fix. Run `git pull && npm install`.

**Comment by khassel** [comment]
works, thank you!
